volumes:
  banking-data:
    name: banking-data

services:
  frontend:
    image: quay.io/masales/banking-frontend:1.0.0
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - banking-network
    environment:
      API_URL: http://fedora-linux:8180/api/accounts
  backend:
    image: quay.io/masales/banking-backend:1.0.0
    container_name: backend
    ports:
      - "8180:8080"
    depends_on:
      - database
    networks:
      - banking-network
    environment:
      POSTGRES_HOST: database
  database:
    image: postgres:17-alpine
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banking
    ports:
      - "5432:5432"
    networks:
      - banking-network
    volumes:
      - banking-data:/var/lib/postgresql/data

networks:
  banking-network:
    driver: bridge